#ifndef CEQUALW2COMPONENT_GLOBAL_H
#define CEQUALW2COMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CEQUALW2COMPONENT_LIBRARY)
#  define CEQUALW2COMPONENT_EXPORT Q_DECL_EXPORT
#else
#  define CEQUALW2COMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // CEQUALW2COMPONENT_GLOBAL_H
